### ISSUE TITLE
Not able to build in maven.

### ISSUE THREAD

**Issue by limeraghu** [MrPowers/spark-stringmetric#12]
I have been using this great package, but for the past two weeks, I have been trying to build my package on my new machine, for some reason, I am getting maven transfer error.

here is the dependency, i am using

<dependency>
    <groupId>MrPowers</groupId>
    <artifactId>spark-stringmetric</artifactId>
    <version>0.2.0</version>
</dependency>

this is coming from 
this artifact is located at SparkPackages repository (https://dl.bintray.com/spark-packages/maven/)

Looks like either file is corrupted or something is missing, please look into it. 

This tool really helped me to have fuzzy logic .

Any help highly appreciated.

Raghu

**Comment by MrPowers** [comment]
@limeraghu - thanks for opening this issue.

I updated the publishing process to follow the "standard Maven" publishing best practices.  You should be able to grab the newer JAR files without any problem.  Here's [where the Scala 2.12 JAR files are stored for example](https://repo1.maven.org/maven2/com/github/mrpowers/spark-stringmetric_2.12/).

Please feel free to reopen this issue is this is still a problem for you.  Thanks again for reporting this!
